name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Yarn
        run: |
          corepack enable
          yarn set version 4.6.0
          yarn --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check Lint
        if: ${{ github.event_name == 'pull_request' }}
        run: yarn lint

      - name: Run Coverage
        run: yarn test:coverage
